name: Deploy Simple Calculator to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Copy files to EC2
      - name: Deploy Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cal.html,ca.css,cal.jpg,calci.html,calci.js,calcii.css"
          target: "/var/www/simple-calculator"

      # Rename cal.html to index.html in server
      - name: Configure Main File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/simple-calculator
            sudo cp cal.html index.html
            sudo systemctl restart nginx
